github: ["nectariferous"]
patreon: ""
open_collective: ""
ko_fi: "nectariferous"
tidelift: ""
community_bridge: ""
liberapay: ""
issuehunt: ""
lfx_crowdfunding: ""
polar: ""
buy_me_a_coffee: "nectariferous"
custom: []
